### PR TITLE
Speed increase for NTLM 8

### PR DESCRIPTION
**Pull request by Sc00bz**

### CODE REVIEW

**Comment by pruby** [comment]
It's clear we've been thinking along similar lines :D 

I think you're going to change results with that though because dividing by 95**4 doesn't guarantee you can fit in a 32-bit int. You're going to need to do a modulo again on the uint64 before trimming to 32 bits to get the same outputs.

**Comment by Sc00bz** [comment]
The max value of `index` is 95\*\*8-1. After divide/modulo the max value for both is 95\*\*4-1 and that fits in a 32 bit int.

**Comment by pruby** [comment]
Ah right, because the modulo is applied in hash_to_index_ntlm8 . Forgot that as it wasn't necessary / didn't make a lot of sense to apply the modulo there before.

**Comment by Sc00bz** [comment]
`index` is what is stored as the start and end points in the rainbow table. So it's common to do a loop of `index`->`password`->`hash`->`index`.

There's Cryptohaze's `password`->`hash`->`password` then `index`->`password` and `password`->`hash` at the beginning and end. He stored the full hash as the end point. Later he reduced it to a partial hash because he didn't want to write `hash`->`password`->`index`. It used lookup tables and parts of the full hash. It was more bias than rcrack. Like for the `[ -~]{8}` key space, `!-9EP\ht` (characters evenly spaced through the character set--that's not the least likely hmm... meh) was less likely than `aaaaaaaa` (characters near each other in the character set). I think fixed point multiple was faster... right that was when `__umul24()` was a thing. It's multiply two 24 bit ints and get a 32 bit answer. Now `__umul24()` is slower than 32 bit multiply.

**Comment by pruby** [comment]
Yeah, I get the point of the index, I just would've defined it differently myself (but that seems to be the original author's choice, not one you've made).

I don't like unchecked preconditions like an assumed range on numerical parameters myself, as they can have unexpected sources. For example, in this case this ignores a second possible source for the index - the start value of a chain. What if someone decided it was too difficult to coordinate generating tables as a group, so just told people to set table starts to a random unsigned long? This doesn't look like it's possible with the current command line, but this extends an implicit precondition to the calling code.

I'm a big believer in defensive programming, so if I were making this decision, the index would be defined as any arbitrary uint64, the modulo operation would be inside the index_to_plaintext and then may as well be removed from the hash to index step. That way, the optimised version would match the original behaviour for all possible inputs.

**Comment by Sc00bz** [comment]
You shouldn't do random start points because of collisions on start points and a random start point is 53 bits (for NTLM 8) and a sequential start point is 36 bits. That's a 32% reduction. If using DIRT file format that's a 30% reduction in chain size ([57.136 bits/chain to 40.136 bits/chain](http://www.tobtu.com/rtcalc.php?reductionFunc=rc&cpTables=1&cpSpeed=1000&cpFileFormat=DIRT&loweralpha&upperalpha&numeric&symbol14&symbol18&space&pwMinLen=8&pwMaxLen=8&cpTotalSuccessRate=86.6666&cpChainLength=421999&sequentialStartPoints&cpdirtCheckPoints=0&cpdirtMagic=2.27&cpdirtHashBits=5&cpdirtMiniIndex=384) check/uncheck "start points: sequential". Settings are for the NTLM 8 table that was generated by this project).

P.S. DIRT file format that never existed because I was too lazy to make it. It uses a MPHF called CHD for the end point (2.27 bits/unique chain). There is an implementation of that in http://cmph.sourceforge.net/ but would need a rewrite to be useful for RTs. There's a mini index that splits it up into ~400 chains per bucket. Each bucket is CHDed. Start points, check points, and extra hash bits are bit packed (vs byte packed). I recently "added" that start points can be partial bits like 36.5 bits. Thus you store 2 start points in 73 bits and divide/modulo by floor(2**36.5). This can save a couple percent on total size.

**Pull request merged**
